
[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.9
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 10
y = 10

[general]
live_config_reload = true
import = ["/home/uzuto/.config/bspwm/alacritty/colors.toml", "/home/uzuto/.config/bspwm/alacritty/fonts.toml"]
